# Generated by Django 3.2.12 on 2022-02-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('openhumans', '0002_openhumansmember_oh_deauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastFmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=256)),
                ('oh_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openhumans.openhumansmember')),
            ],
        ),
    ]
